
INSERT INTO _Help_Desk_Schedule (staff_id, shift_id, day) VALUES
(?, 1, ?),
(?, 2, ?),
(?, 3, ?),
(?, 4, ?),
(?, 5, ?),
()?, 6, ?),
(?, 7, ?),
(?, 8, ?),
(?, 9, ?),
(?, 10, ?),
(?, 11, ?),
(?, 12, ?),
(?, 13, ?),
(?, 14, ?),
(?, 15, ?),
(?, 16, ?),
(?, 17, ?),
(?, 18, ?),
(?, 19, ?),
(?, 20, ?),
(?, 21, ?),
(?, 22, ?),
(?, 23, ?),
(?, 24, ?),
(?, 25, ?),
(?, 26, ?),
(?, 27, ?),
(?, 28, ?),
(?, 29, ?),
(?, 30, ?),
(?, 31, ?),
(?, 32, ?),
(?, 33, ?),
(?, 34, ?),
(?, 35, ?),
(?, 36, ?),
(?, 37, ?),
(?, 38, ?),
(?, 39, ?),
(?, 40, ?),
(?, 41, ?),
(?, 42, ?),
(?, 43, ?),
(?, 44, ?),
(?, 45, ?),
(?, 46, ?),
(?, 47, ?),
(?, 48, ?),
(?, 49, ?),
(?, 50, ?),
(?, 51, ?),
(?, 52, ?),
(?, 53, ?),
(?, 54, ?),
(?, 55, ?),
(?, 56, ?),
(?, 57, ?),
(?, 58, ?),
(?, 59, ?),
(?, 60, ?),
(?, 61, ?),
(?, 62, ?),
(?, 63, ?),
(?, 64, ?),
(?, 65, ?),
(?, 66, ?),
(?, 67, ?),
(?, 68, ?),
(?, 69, ?),
(?, 70, ?),
(?, 71, ?),
(?, 72, ?),
(?, 73, ?),
(?, 74, ?),
(?, 75, ?),
(?, 76, ?),
(?, 77, ?),
(?, 78, ?),
(?, 79, ?),
(?, 80, ?),
(?, 81, ?),
(?, 82, ?),
(?, 83, ?),
(?, 84, ?),
(?, 85, ?),
(?, 86, ?),
(?, 87, ?),
(?, 88, ?),
(?, 89, ?),
(?, 90, ?),
(?, 91, ?);




#inserts needed to build the schedules is here to help with formatting

 [shiftPostion[1], monday,
  shiftPostion[2], monday,
  shiftPostion[3], monday,
	shiftPostion[4], monday,
	shiftPostion[5], monday,
	shiftPostion[6], monday,
	shiftPostion[7], monday,
	shiftPostion[8], monday,
	shiftPostion[9], monday,
	shiftPostion[10], monday,
	shiftPostion[11], monday,
	shiftPostion[12], monday,
	shiftPostion[13], monday,
	shiftPostion[14], tuesday,
  shiftPostion[15], tuesday,
  shiftPostion[16], tuesday,
 	shiftPostion[17], tuesday,
 	shiftPostion[17], tuesday,
 	shiftPostion[19], tuesday,
 	shiftPostion[20], tuesday,
 	shiftPostion[21], tuesday,
 	shiftPostion[22], tuesday,
 	shiftPostion[23], tuesday,
 	shiftPostion[24], tuesday,
 	shiftPostion[25], tuesday,
 	shiftPostion[26], tuesday,
	shiftPostion[27], wednesday,
	shiftPostion[28], wednesday,
	shiftPostion[29], wednesday,
	shiftPostion[30], wednesday,
	shiftPostion[31], wednesday,
	shiftPostion[32], wednesday,
	shiftPostion[33], wednesday,
	shiftPostion[34], wednesday,
	shiftPostion[35], wednesday,
	shiftPostion[36], wednesday,
	shiftPostion[37], wednesday,
	shiftPostion[38], wednesday,
	shiftPostion[39], wednesday,
	shiftPostion[40], thursday,
	shiftPostion[41], thursday,
	shiftPostion[42], thursday,
	shiftPostion[43], thursday,
	shiftPostion[44], thursday,
	shiftPostion[45], thursday,
	shiftPostion[46], thursday,
	shiftPostion[47], thursday,
	shiftPostion[48], thursday,
	shiftPostion[49], thursday,
	shiftPostion[50], thursday,
	shiftPostion[51], thursday,
	shiftPostion[52], thursday,
	shiftPostion[53], friday,
	shiftPostion[54], friday,
	shiftPostion[55], friday,
	shiftPostion[56], friday,
	shiftPostion[57], friday,
	shiftPostion[58], friday,
	shiftPostion[59], friday,
	shiftPostion[60], friday,
	shiftPostion[61], friday,
	shiftPostion[62], friday,
	shiftPostion[63], friday,
	shiftPostion[64], friday,
	shiftPostion[65], friday,
	shiftPostion[66], saturday,
	shiftPostion[67], saturday,
	shiftPostion[68], saturday,
	shiftPostion[69], saturday,
	shiftPostion[70], saturday,
	shiftPostion[71], saturday,
	shiftPostion[72], saturday,
	shiftPostion[73], saturday,
	shiftPostion[74], saturday,
	shiftPostion[75], saturday,
	shiftPostion[76], saturday,
	shiftPostion[77], saturday,
	shiftPostion[78], saturday,
	shiftPostion[79], sunday,
	shiftPostion[80], sunday,
	shiftPostion[81], sunday,
	shiftPostion[82], sunday,
	shiftPostion[83], sunday,
	shiftPostion[84], sunday,
	shiftPostion[85], sunday,
	shiftPostion[86], sunday,
	shiftPostion[87], sunday,
	shiftPostion[88], sunday,
	shiftPostion[89], sunday,
	shiftPostion[90], sunday,
	shiftPostion[91], sunday]
