INSERT INTO _Lab_Schedule (staff_id, shift_id, day) VALUES
(?, 1, ?),
(?, 2, ?),
(?, 3, ?),
(?, 4, ?),
(?, 5, ?),
()?, 6, ?),
(?, 7, ?),
(?, 8, ?),
(?, 9, ?),
(?, 10, ?),
(?, 11, ?),
(?, 12, ?),
(?, 13, ?),
(?, 14, ?),
(?, 15, ?),
(?, 16, ?),
(?, 17, ?),
(?, 18, ?),
(?, 19, ?),
(?, 20, ?),
(?, 21, ?),
(?, 22, ?),
(?, 23, ?),
(?, 24, ?),
(?, 25, ?),
(?, 26, ?),
(?, 27, ?),
(?, 28, ?),
(?, 29, ?),
(?, 30, ?),
(?, 31, ?),
(?, 32, ?),
(?, 33, ?),
(?, 34, ?),
(?, 35, ?),
(?, 36, ?),
(?, 37, ?),
(?, 38, ?),
(?, 39, ?),
(?, 40, ?),
(?, 41, ?),
(?, 42, ?),
(?, 43, ?),
(?, 44, ?),
(?, 45, ?),
(?, 46, ?),
(?, 47, ?),
(?, 48, ?),
(?, 49, ?),
(?, 50, ?),
(?, 51, ?),
(?, 52, ?),
(?, 53, ?),
(?, 54, ?),
(?, 55, ?),
(?, 56, ?),
(?, 57, ?),
(?, 58, ?),
(?, 59, ?),
(?, 60, ?),
(?, 61, ?),
(?, 62, ?),
(?, 63, ?),
(?, 64, ?),
(?, 65, ?),
(?, 66, ?),
(?, 67, ?),
(?, 68, ?),
(?, 69, ?),
(?, 70, ?),
(?, 71, ?),
(?, 72, ?),
(?, 73, ?),
(?, 74, ?),
(?, 75, ?),
(?, 76, ?),
(?, 77, ?),
(?, 78, ?),
(?, 79, ?),
(?, 80, ?),
(?, 81, ?),
(?, 82, ?),
(?, 83, ?),
(?, 84, ?),
(?, 85, ?),
(?, 86, ?),
(?, 87, ?),
(?, 88, ?),
(?, 89, ?),
(?, 90, ?),
(?, 91, ?);




#inserts needed to build the schedules is here to help with formatting

[shiftPostion[1], monday.format(),
 shiftPostion[2], monday.format(),
 shiftPostion[3], monday.format(),
 shiftPostion[4], monday.format(),
 shiftPostion[5], monday.format(),
 shiftPostion[6], monday.format(),
 shiftPostion[7], monday.format(),
 shiftPostion[8], monday.format(),
 shiftPostion[9], monday.format(),
 shiftPostion[10], monday.format(),
 shiftPostion[11], monday.format(),
 shiftPostion[12], monday.format(),
 shiftPostion[13], monday.format(),

 shiftPostion[14], tuesday.format(),
 shiftPostion[15], tuesday.format(),
 shiftPostion[16], tuesday.format(),
 shiftPostion[17], tuesday.format(),
 shiftPostion[18], tuesday.format(),
 shiftPostion[19], tuesday.format(),
 shiftPostion[20], tuesday.format(),
 shiftPostion[21], tuesday.format(),
 shiftPostion[22], tuesday.format(),
 shiftPostion[23], tuesday.format(),
 shiftPostion[24], tuesday.format(),
 shiftPostion[25], tuesday.format(),
 shiftPostion[26], tuesday.format(),

 shiftPostion[27], wednesday.format(),
 shiftPostion[28], wednesday.format(),
 shiftPostion[29], wednesday.format(),
 shiftPostion[30], wednesday.format(),
 shiftPostion[31], wednesday.format(),
 shiftPostion[32], wednesday.format(),
 shiftPostion[33], wednesday.format(),
 shiftPostion[34], wednesday.format(),
 shiftPostion[35], wednesday.format(),
 shiftPostion[36], wednesday.format(),
 shiftPostion[37], wednesday.format(),
 shiftPostion[38], wednesday.format(),
 shiftPostion[39], wednesday.format(),

 shiftPostion[40], thursday.format(),
 shiftPostion[41], thursday.format(),
 shiftPostion[42], thursday.format(),
 shiftPostion[43], thursday.format(),
 shiftPostion[44], thursday.format(),
 shiftPostion[45], thursday.format(),
 shiftPostion[46], thursday.format(),
 shiftPostion[47], thursday.format(),
 shiftPostion[48], thursday.format(),
 shiftPostion[49], thursday.format(),
 shiftPostion[50], thursday.format(),
 shiftPostion[51], thursday.format(),
 shiftPostion[52], thursday.format(),

 shiftPostion[53], friday.format(),
 shiftPostion[54], friday.format(),
 shiftPostion[55], friday.format(),
 shiftPostion[56], friday.format(),
 shiftPostion[57], friday.format(),
 shiftPostion[58], friday.format(),
 shiftPostion[59], friday.format(),
 shiftPostion[60], friday.format(),
 shiftPostion[61], friday.format(),
 shiftPostion[62], friday.format(),
 shiftPostion[63], friday.format(),
 shiftPostion[64], friday.format(),
 shiftPostion[65], friday.format(),

 shiftPostion[66], saturday.format(),
 shiftPostion[67], saturday.format(),
 shiftPostion[68], saturday.format(),
 shiftPostion[69], saturday.format(),
 shiftPostion[70], saturday.format(),
 shiftPostion[71], saturday.format(),
 shiftPostion[72], saturday.format(),
 shiftPostion[73], saturday.format(),
 shiftPostion[74], saturday.format(),
 shiftPostion[75], saturday.format(),
 shiftPostion[76], saturday.format(),
 shiftPostion[77], saturday.format(),
 shiftPostion[78], saturday.format(),

 shiftPostion[79], sunday.format(),
 shiftPostion[80], sunday.format(),
 shiftPostion[81], sunday.format(),
 shiftPostion[82], sunday.format(),
 shiftPostion[83], sunday.format(),
 shiftPostion[84], sunday.format(),
 shiftPostion[85], sunday.format(),
 shiftPostion[86], sunday.format(),
 shiftPostion[87], sunday.format(),
 shiftPostion[88], sunday.format(),
 shiftPostion[89], sunday.format(),
 shiftPostion[90], sunday.format(),
 shiftPostion[91], sunday.format()]
